### PR TITLE
Remove Boost and move to Chaiscript 5.1

### PR DESCRIPTION
**Pull request by da2ce7**
I have updated the project files so that we (optionally) make use of C++11

In the process I've removed all our dependences on boost (via ChaiScript) by upgrading to ChaiScript 5.1

The install documentation (for Mac OS X and Windows) has been updated and simplified.  However the Linux install documentation still need to be updated... However should keep on working as before.

This pull request still needs testing... But is functional.

Cam.

### CODE REVIEW

**Comment by da2ce7** [comment]
Oh yeah... please don't pull this yet.

**Comment by theontho** [comment]
This is great, once you finish this I can push my chaiscript & OT homebrew build scripts for OT.

The homebrew scripts are here if you want to play with them:
https://github.com/mahyar/Open-Transactions/tree/master/osx

**Comment by da2ce7** [comment]
Prob, ok, to pull, after testing.

**Comment by da2ce7** [comment]
Progress. Now Chaiscript seems to load. However it dosn't like the ot scripts.
http://pastebin.com/J0XejtH3

**Comment by da2ce7** [comment]
All updated! Thanks to pigeons, found a few more bugs.

**Pull request merged**
