### PR TITLE
Fixed python api

### PR DESCRIPTION
**Pull request by BlueWall**
Made changes to python api. Builds, lib imports w/o error and tests described in API-README.txt pass. This is on Linux, 64 bits

Thanks

### CODE REVIEW

**Comment by FellowTraveler** [comment]
On 2/13/12 12:17 PM, BlueWall (James Hughes) wrote:

> M testwallet/OTAPI_python.cpp (10)
> M testwallet/otapi.py (2254)

FYI these two files:

M testwallet/OTAPI_python.cpp (10)
M testwallet/otapi.py (2254)

I do not write these files by hand -- these files were generated
automatically by SWIG.

Every time the OT interface changes, SWIG will REGENERATE those files
and your changes will be lost.

===> Therefore any changes like this, for them to STICK, you need to
make all of your changes in testwallet/OTAPI.i and testwallet/buildwrappers

===> Those files, run with SWIG, are what will generate the actual
OTAPI_python.cpp and otapi.py files.

Does that make sense?

**Comment by BlueWall** [comment]
yes, I'll dig into those. I don't know enough about it to tell if it will break other things.

**Comment by FellowTraveler** [comment]
On 2/13/12 12:43 PM, BlueWall (James Hughes) wrote:

> yes, I'll dig into those. I don't know enough about it to tell if it will break other things.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FellowTraveler/Open-Transactions/pull/65#issuecomment-3948882

Pls see these notes also:

http://www.swig.org/Doc2.0/Introduction.html#Introduction_nn8

http://www.swig.org/Doc2.0/Python.html#Python

http://www.swig.org/Doc1.3/Python.html

**Comment by BlueWall** [comment]
OK, Got it. Reverted the earlier changes. Needed to make a couple of changes in the ./testwallet/Makefile.API to get the right headers instead of using hard-coded values. Also, the python lib needed to be named _otapi.so . That is OK, because it can be placed in the  python site-packages directory. and now the fixes survive buildwrappers.

**Pull request merged**
