### PR TITLE
Various Cleanups and Windows Fixes

### PR DESCRIPTION
**Pull request by da2ce7**
This pull request just contains some preparation work for the C++ API
1. Changed some of the asserts in OTAPI.cpp
2. Regenerated the swig wrappers.
3. Fixed a few linker errors on windows.
4. Enabled support for PHP wrapper on windows.

### CODE REVIEW

**Comment by da2ce7** [comment]
https://github.com/FellowTraveler/Moneychanger/pull/28

**Comment by jspit** [comment]
Hi

I managed to compile the otapi-warp -  java library

But there is something wrong with the php one.

3>  OTAPI-php.cpp

3>C:\Program Files\Microsoft Visual Studio 11.0\VC\include\stdio.h(615):
warning C4273: 'getwchar' : inconsistent dll linkage
3>          C:\Program Files\Microsoft Visual Studio
11.0\VC\include\stdio.h(426) : see previous definition of 'getwchar'
3>C:\Program Files\Microsoft Visual Studio 11.0\VC\include\stdio.h(617):
warning C4273: 'putwchar' : inconsistent dll linkage
3>          C:\Program Files\Microsoft Visual Studio
11.0\VC\include\stdio.h(428) : see previous definition of 'putwchar'
3>C:\Open-Transactions\include\php\main\php.h(268): warning C4273:
'_environ' : inconsistent dll linkage
3>          C:\Program Files\Microsoft Visual Studio
11.0\VC\include\stdlib.h(298) : see previous definition of '_environ'
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\sys/stat.inl(42): error C2466: cannot allocate an array of
constant size 0
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\sys/stat.inl(47): error C2466: cannot allocate an array of
constant size 0
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\sys/utime.inl(37): error C2466: cannot allocate an array of
constant size 0
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\sys/utime.inl(42): error C2466: cannot allocate an array of
constant size 0
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\sys/utime.inl(47): error C2466: cannot allocate an array of
constant size 0
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\sys/utime.inl(76): error C2466: cannot allocate an array of
constant size 0
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\xkeycheck.h(199): warning C4005: 'inline' : macro
redefinition
3>          c:\open-transactions\include\php\tsrm\tsrm_config.w32.h(18) :
see previous definition of 'inline'
3>C:\Program Files\Microsoft Visual Studio
11.0\VC\include\xkeycheck.h(242): fatal error C1189: #error :  The C++
Standard Library forbids macroizing keywords. Enable warning C4005 to find
the forbidden macro.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 7 skipped ==========

Jes

**Comment by jspit** [comment]
Managed to compile the the csharp library as well

Problem is with the php - there is something wrong in stdio.h

**Comment by da2ce7** [comment]
FT:  I've included your %newobject directives; and been checking it with a memory leak detector on windows.
I haven't been able to detect any leaks (since java now owns the objects with the newobject).

https://github.com/da2ce7/Open-Transactions/blob/aae435c9c5509f1038ab33ccbb13f8114b8bffd9/swig/otapi/OTAPI.i

I think that this is good to pull...  My c++api should get a bit more testing tho.

**Comment by jspit** [comment]
Cameron

Since I manage to compile otserver ,  csharp and java but not php, could it
be that is is something to that i have a 32 bit computer ?

In your install instructions - you said that it was tested on windows 7 64
bit

I have VS Studio 12, VS 12 Redistributable (and not 2008
redistributalbles), downloaded the php binaries

I change the otapi.i but same errors are coming up.

> C:\Program Files\Microsoft Visual Studio 11.0\VC\include\stdio.h(615):
> warning C4273: 'getwchar' : inconsistent dll linkage
> 1>          C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\stdio.h(426) : see previous definition of 'getwchar'
> 1>C:\Program Files\Microsoft Visual Studio 11.0\VC\include\stdio.h(617):
> warning C4273: 'putwchar' : inconsistent dll linkage
> 1>          C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\stdio.h(428) : see previous definition of 'putwchar'
> 1>C:\Open-Transactions\include\php\main\php.h(268): warning C4273:
> '_environ' : inconsistent dll linkage
> 1>          C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\stdlib.h(298) : see previous definition of '_environ'
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\sys/stat.inl(43): error C2466: cannot allocate an array of
> constant size 0
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\sys/stat.inl(48): error C2466: cannot allocate an array of
> constant size 0
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\sys/utime.inl(38): error C2466: cannot allocate an array of
> constant size 0
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\sys/utime.inl(43): error C2466: cannot allocate an array of
> constant size 0
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\sys/utime.inl(48): error C2466: cannot allocate an array of
> constant size 0
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\sys/utime.inl(77): error C2466: cannot allocate an array of
> constant size 0
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\xkeycheck.h(199): warning C4005: 'inline' : macro
> redefinition
> 1>          c:\open-transactions\include\php\tsrm\tsrm_config.w32.h(18) :
> see previous definition of 'inline'
> 1>C:\Program Files\Microsoft Visual Studio
> 11.0\VC\include\xkeycheck.h(242): fatal error C1189: #error :  The C++
> Standard Library forbids macroizing keywords. Enable warning C4005 to find
> the forbidden macro.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Could it be a compatability issue ?

On 6 November 2012 06:52, Cameron Garnham notifications@github.com wrote:

> FT: I've included your %newobject directives; and been checking it with a
> memory leak detector on windows.
> I haven't been able to detect any leaks (since java now owns the objects
> with the newobject).
> 
> https://github.com/da2ce7/Open-Transactions/blob/aae435c9c5509f1038ab33ccbb13f8114b8bffd9/swig/otapi/OTAPI.i
> 
> I think that this is good to pool... My c++api should get a bit more
> testing tho.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FellowTraveler/Open-Transactions/pull/125#issuecomment-10100033.

## 

Jesmond Spiteri

**Comment by jspit** [comment]
Where can I get

main\config.w32.h
zend\zend_config.h

These are not being found on compilation.

Jes

On 6 November 2012 06:52, Cameron Garnham notifications@github.com wrote:

> FT: I've included your %newobject directives; and been checking it with a
> memory leak detector on windows.
> I haven't been able to detect any leaks (since java now owns the objects
> with the newobject).
> 
> https://github.com/da2ce7/Open-Transactions/blob/aae435c9c5509f1038ab33ccbb13f8114b8bffd9/swig/otapi/OTAPI.i
> 
> I think that this is good to pool... My c++api should get a bit more
> testing tho.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FellowTraveler/Open-Transactions/pull/125#issuecomment-10100033.

## 

Jesmond Spiteri

**Comment by FellowTraveler** [comment]
On 11/5/12 1:42 AM, Jesmond Spiteri wrote:

> Managed to compile the the csharp library as well
> 
> Problem is with the php - there is something wrong in stdio.h
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FellowTraveler/Open-Transactions/pull/125#issuecomment-10064802.

stdio.h ????

Shouldn't that be  cstdio ??

e.g. :

#include <cstdio>

NOT!  #include <stdio.h>

the first example is correct. The second is deprecated.

**Comment by da2ce7** [comment]
yep...  had stdio.h and stdlib.h in some places.... now replaced with cstdio and cstdlib

will recompile and test. (on win, mac and linux)

**Pull request merged**
