### PR TITLE
New OTSettings.h, OTPaths.h; reworked OTSocket, clean OTLog

### PR DESCRIPTION
**Pull request by da2ce7**
This pull request contains a backport of much of the work that I did in my c++x11 branch (without any c++x11 dependencies).

All of the paths and settings code has been moved out of OTLog.

OTAPI_Wrap now makes sure that things are destructed in the correct order. (and no need to explicitly call OT_API::Init() any more).

All the folder names can be set in the config now.

TransportCallback now is a struct, that references a member function in OT_API.  (no longer a static function).

### CODE REVIEW

**Comment by jspit** [comment]
downloaded all from your version of open-transactions\

all compiled even though there were a lot of warnings

the otapi-php will only compile with vs2010

tried to run moneychanger and the following error comes up

Exception in thread "main" java.lang.NoSuchMethodError:
SwigDirector_OTCallback_runOne
        at org.opentransactions.jni.core.otapiJNI.swig_module_init(Native
Method)
        at
org.opentransactions.jni.core.otapiJNI.<clinit>(otapiJNI.java:850)
        at com.moneychanger.ui.Load.Init(Load.java:123)
        at
com.moneychanger.app.Moneychanger$Loader.Load(Moneychanger.java:108)
        at com.moneychanger.app.Moneychanger.main(Moneychanger.java:98)

Press any key to continue . . .

in moneychanger, what method did you use to pass on the password to the
server ? ie successful log-in.

thanks
any clues ?

On 18 December 2012 10:23, Cameron Garnham notifications@github.com wrote:

> This pull request contains a backport of much of the work that I did in my
> c++x11 branch (without any c++x11 dependencies).
> 
> All of the paths and settings code has been moved out of OTLog.
> 
> OTAPI_Wrap now makes sure that things are destructed in the correct order.
> (and no need to explicitly call OT_API::Init() any more).
> 
> All the folder names can be set in the config now.
> 
> TransportCallback now is a struct, that references a member function in
> 
> ## OT_API. (no longer a static function).
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/da2ce7/Open-Transactions master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/FellowTraveler/Open-Transactions/pull/137
> Commit Summary
> - v0.88.a: Setting and Socket changes.
> - fix so zmq quit's in correct order
> 
> File Changes
> - _M_ VERSION (2)
> - _M_ include/otapi/OTAPI.h (11)
> - _M_ include/otapi/OTClient.h (2)
> - _M_ include/otapi/OTServerConnection.h (14)
> - _M_ include/otapi/OpenTransactions.h (149)
> - _M_ include/otapi/otapicli.h (2)
> - _M_ include/otlib/OTLog.h (322)
> - _M_ include/otlib/OTMessageBuffer.h (5)
> - _A_ include/otlib/OTPaths.h (366)
> - _M_ include/otlib/OTSettings.h (65)
> - _M_ include/otlib/OTStorage.h (2)
> - _M_ include/otlib/OTString.h (44)
> - _M_ include/otlib/OTWallet.h (1)
> - _M_ include/ots/OTServer.h (6)
> - _M_ project/ot/ot.vcxproj (129)
> - _M_ project/ot/ot.vcxproj.filters (137)
> - _M_ project/otapi/otapi.vcxproj (143)
> - _M_ project/otapi/otapi.vcxproj.filters (137)
> - _M_ project/otlib/otlib.vcxproj (3)
> - _M_ project/otlib/otlib.vcxproj.filters (9)
> - _M_ src/otapi/OTAPI.cpp (110)
> - _M_ src/otapi/OTAPI_Basic.cpp (2)
> - _M_ src/otapi/OTClient.cpp (85)
> - _M_ src/otapi/OTServerConnection.cpp (11)
> - _M_ src/otapi/OT_ME.cpp (70)
> - _M_ src/otapi/OpenTransactions.cpp (1453)
> - _M_ src/otapi/otapicli.cpp (24)
> - _M_ src/otd/main.cpp (35)
> - _M_ src/otlib/Makefile.am (4)
> - _M_ src/otlib/OTAccount.cpp (19)
> - _M_ src/otlib/OTAssetContract.cpp (14)
> - _M_ src/otlib/OTContract.cpp (2)
> - _M_ src/otlib/OTCron.cpp (6)
> - _M_ src/otlib/OTCronItem.cpp (4)
> - _M_ src/otlib/OTLedger.cpp (30)
> - _M_ src/otlib/OTLog.cpp (2075)
> - _M_ src/otlib/OTMarket.cpp (6)
> - _M_ src/otlib/OTMessageBuffer.cpp (28)
> - _M_ src/otlib/OTMint.cpp (12)
> - _A_ src/otlib/OTPaths.cpp (1428)
> - _M_ src/otlib/OTPseudonym.cpp (28)
> - _M_ src/otlib/OTPurse.cpp (8)
> - _M_ src/otlib/OTSettings.cpp (402)
> - _M_ src/otlib/OTSmartContract.cpp (30)
> - _M_ src/otlib/OTStorage.cpp (71)
> - _M_ src/otlib/OTString.cpp (31)
> - _M_ src/otlib/OTToken.cpp (24)
> - _M_ src/otlib/OTTransaction.cpp (16)
> - _M_ src/otlib/OTWallet.cpp (12)
> - _M_ src/otmint/main.cpp (37)
> - _M_ src/ots/OTServer.cpp (362)
> - _M_ src/ots/xmlrpcxx_server.cpp (300)
> 
> Patch Links
> - https://github.com/FellowTraveler/Open-Transactions/pull/137.patch
> - https://github.com/FellowTraveler/Open-Transactions/pull/137.diff
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/FellowTraveler/Open-Transactions/pull/137.

## 

Jesmond Spiteri

**Comment by da2ce7** [comment]
New Windows Builds: https://drive.google.com/#folders/0B1vBlIVORn8nVFRJTzNnc3Y5Rm8

**Comment by jspit** [comment]
Great work Cameron

when you run the php_ot_test.php from the browser

the following is being written in ot-clinet log

OTPseudonym::Loadx509CertAndPrivateKey: Although the ascii-armored file
(certs/T1Q3wZWgeTUoaUvn9m1lzIK5tn5wITlzxzrGNI8qtaV) was read,
LoadPrivateKey returned false.
OTPseudonym::LoadPrivateNym OT_API::getAccount: Failure calling
Loadx509CertAndPrivateKey: T1Q3wZWgeTUoaUvn9m1lzIK5tn5wITlzxzrGNI8qtaV
OTWallet::GetOrLoadPrivateNym OT_API::getAccount: Unable to load private
Nym for: T1Q3wZWgeTUoaUvn9m1lzIK5tn5wITlzxzrGNI8qtaV

should this be the case ?

On 19 December 2012 05:56, Cameron Garnham notifications@github.com wrote:

> New Windows Builds:
> https://drive.google.com/#folders/0B1vBlIVORn8nVFRJTzNnc3Y5Rm8
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/FellowTraveler/Open-Transactions/pull/137#issuecomment-11517565.

## 

Jesmond Spiteri

**Comment by jspit** [comment]
Cameron

FYI

Windows dependancies - solved

you have to run apache as a service - otherwise it will be calling the windows system account account.

**Comment by jspit** [comment]
php test script

when you ran the script for php, did it hang on LoadWallet() as it should be expecting a password from user or where you using special data

**Comment by jspit** [comment]
Hi Cameron

any new updates re window Builds:
https://drive.google.com/#folders/0B1vBlIVORn8nVFRJTzNnc3Y5Rm8
? https://drive.google.com/#folders/0B1vBlIVORn8nVFRJTzNnc3Y5Rm8

i had to upgrade php to 5.5 and the otapi-php.dll extensions won't load due
to mismatch found in dll.

Thanks
Regards
Jesmond
https://drive.google.com/#folders/0B1vBlIVORn8nVFRJTzNnc3Y5Rm8

On 19 December 2012 05:56, Cameron Garnham notifications@github.com wrote:

> New Windows Builds:
> https://drive.google.com/#folders/0B1vBlIVORn8nVFRJTzNnc3Y5Rm8
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/FellowTraveler/Open-Transactions/pull/137#issuecomment-11517565.

## 

Jesmond Spiteri

**Comment by da2ce7** [comment]
agah... those builds are old!

**Comment by da2ce7** [comment]
you really should be building your own version.

**Comment by jspit** [comment]
ok - no problem 
i dowloaded the latest version of open-transactions and chainscript and all the rest and tried to compile using visual studio 2013 - too many erros during compilation due to configuration issue.

But thanks anyway.

**Pull request merged**
