### PR TITLE
Kill warnings.

### PR DESCRIPTION
**Pull request by benlaurie**
I like things to build with -Wall -Werror, so the second commit does that for the OTLib directory, but again you probably don't want all of it, since some is platform dependent. The configure script I mentioned deals with stuff like format strings for time_t, btw...

I notice that irlxml is actually irrxml, too...

### CODE REVIEW

**Comment by FellowTraveler** [comment]
1) Looks like you did work to clean warnings AND to add FreeBSD to the list of platforms. 

On both counts, I _definitely_ want to merge this back in to the main source. I am slammed today with RL stuff but maybe tomorrow or the next day I'll get your stuff building for my platforms and then check it all back in.

Q: Is there an #ifdef I can use for FreeBSD? I'll google this otherwise but maybe you save me time.

2) Yes you caught me on irlxml.  By the time I caught it, became my lowest priority :D

3) Did you ever get it running?  It should run on Linux and Mac no problem at all.
If you had problems connecting on FreeBSD, I bet it's in the SSL / TCP code. It took me like 2 days to port it all to Windows and it didn't connect there at first, either. Just brainstorming.

**Comment by benlaurie** [comment]
**FreeBSD** is the variable you need to test for.

I did not get it running.

**Comment by FellowTraveler** [comment]
I fixed irlxml... changed to irrxml.

I also merged most of your commits.  I had to change a few things back so it would build for me (Werror was breaking the build... plus your OpenSSL path was hardcoded to "ben" in the Makefile so had to fix that.)

**Comment by benlaurie** [comment]
Yes, you need to do additional work to make -Werror work cross-platform (e.g. per platform format strings). I did offer to help with that.

**Comment by FellowTraveler** [comment]
Any help you are offering is gratefully accepted.

I'm in the middle of overhauling the logging code and the i/o, so you might want to wait until I post that, but I'll email you when I do.

**Pull request merged**
