### PR TITLE
FreeBSD port

### PR DESCRIPTION
**Pull request by benlaurie**
I don't expect you'll want to pull all of this, since some of it is incompatible, but I didn't want to go further down the road without figuring out how you'd like the cross-platform stuff to proceed...

I hate autoconf et al, myself, so I'm not going to offer to do that, but if you want to depart from the beaten path, I could adapt the configure script I used for OpenPGP:SDK (written in Perl) to deal with the platform dependencies...

Also, although this builds and mostly works, if I run transaction.exe (btw, sucky name for a *nix platform) and testwallet.exe, testwallet fails to connect to the server...

### CODE REVIEW

**Comment by FellowTraveler** [comment]
I wish I had time to go over this today...

1) For now all the platforms work in the same codebase, using #ifdefs. Hopefully the changes for FreeBSD can be similarly wrapped and keep everything clean. Any Makefile or configure contributions that you have are appreciated.

2) transaction.exe was named to make things convenient for a Windows developer who is volunteering to create a Java client and maybe Android. To support him, I ported the code to Windows. Visual C++ also created a conflict with the Open-Transactions\transaction\transaction folder, so renaming the executable fixed that as well. He's finicky but he's free.

**Comment by FellowTraveler** [comment]
One more thing -- can you get me a test account or a VM on a FreeBSD box so I can login and debug (like if it won't connect.)  Someone already gave me a Linux VM which is why I ported it to Linux in the first place.

**Comment by benlaurie** [comment]
I don't know where to get an account for you. I'd suggest building a VM of your own. I'm told the PC-BSD live image is easy to get on with...

**Comment by FellowTraveler** [comment]
Okay this is all merged in.  I'll look into installing a FreeBSD VM so I can fix the socket bug you're having (after all, that's how I ported it to Windows -- I used Parallels.)

**Pull request merged**
